_format_version: "3.0"
_transform: true

services:
  - name: orders
    url: http://host.docker.internal:3333 # Nosso localhost pelo config do docker
    protocol: http
    host: host.docker.internal
    port: 3333
    path: / 
    routes:
      - name: api-orders
        protocols:
          - http
          - https
        paths:
          - '/orders' # apigateway.com/orders faz uma requisição na api de orders

  - name: invoices
    url: http://host.docker.internal:3334 # Nosso localhost pelo config do docker
    protocol: http
    host: host.docker.internal
    port: 3334
    path: / 
    routes:
      - name: api-invoices
        protocols:
          - http
          - https
        paths:
          - '/invoices' # apigateway.com/invoices faz uma requisição na api de invoices

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization